name: pixel_adventure
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.30.0
  flame_tiled: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/tiles/
    - assets/images/Background/
    - assets/images/Terrain/
    - assets/images/HUB/
    - assets/images/Traps/Saw/
    - assets/images/Items/Checkpoints/Checkpoint/
    - assets/images/Items/Fruits/
    - assets/images/Main Characters/
    - assets/images/Main Characters/Mask Dude/
    - assets/images/Main Characters/Ninja Frog/
    - assets/images/Main Characters/Pink Man/
    - assets/images/Main Characters/Virtual Guy/
    - assets/images/Enemies/Chicken/
